CREATE TABLE ITEM(
ItemID CHAR(6) NOT NULL,
ItemDescription VARCHAR2(100) NOT NULL,
Volume_ml NUMBER NOT NULL,
Cost NUMBER NOT NULL,
Retail NUMBER NOT NULL,
Sales NUMBER NOT NULL,
VolumeSold_l NUMBER NOT NULL,
CONSTRAINT ITEM_PK PRIMARY KEY (ItemID)
);